name: Assign self to PR

on:
  pull_request:
    types: [ opened ]
    branches:
      - master
      - main

jobs:
  assign_author:
    runs-on: ubuntu-latest
    steps:
      - uses: samspills/assign-pr-to-author@v1.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
