name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          check-latest: true
          java-version: 23
          cache: 'gradle'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Run detekt
        run: ./gradlew detektAll

      - name: Build
        run: ./gradlew assemble --stacktrace --no-configuration-cache

      - name: Unit tests
        run: ./gradlew allTests --stacktrace --no-configuration-cache
